name: Gitleaks Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go (for gitleaks)
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Install Gitleaks
      run: go install github.com/zricethezav/gitleaks/v8@latest

    - name: Run Gitleaks
      run: |
        gitleaks detect --source . --report-path gitleaks_report.json
        if [ -s gitleaks_report.json ]; then
          echo "Se encontraron fugas de información. Revisa gitleaks_report.json."
          exit 1
        else
          echo "No se encontraron fugas."
        fi

    - name: Upload report
      if: failure()
      uses: actions/upload-artifact@v4  # Asegúrate de usar la versión 4
      with:
        name: gitleaks-report
        path: gitleaks_report.json
